"""empty message

Revision ID: 75d48e07df21
Revises: 915c25ffc69a
Create Date: 2022-05-16 09:44:45.553513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d48e07df21'
down_revision = '915c25ffc69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('hashtags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'hashtags')
    # ### end Alembic commands ###
