"""empty message

Revision ID: 796b71e0f632
Revises: 
Create Date: 2022-06-19 11:32:19.859876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796b71e0f632'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificpost', sa.Column('comment_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notificpost', 'comment_id')
    # ### end Alembic commands ###
